kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
- name: docker
  image: plugins/docker
  settings:
    repo: repo.treescale.com
    registry: kharloss/glances
    username:
      from_secret: treescale_username
    password:
      from_secret: treescale_password
      auto_tag: true
    auto_tag_suffix: drone-build